/* Local headphone monitoring and optional stereo export. Uses unmodified Omnitone. */
(()=>{
 const $=id=>document.getElementById(id),select=$('audio-recording'),play=$('audio-play'),stop=$('audio-stop'),seek=$('audio-position'),exportButton=$('binaural-export'),status=$('audio-status');
 let entries=[],busy=false,exporting=false,context=null,graph=null,source=null,loaded=null,buffer=null,offset=0,started=0,timer=null,loading=false;
 const xyz=[3,1,2];
 function rotation(){const v=k=>(Number($(k).value)||0)*Math.PI/180,y=v('yaw'),p=v('pitch'),r=v('roll'),cy=Math.cos(y),sy=Math.sin(y),cp=Math.cos(p),sp=Math.sin(p),cr=Math.cos(r),sr=Math.sin(r);return [cy*cp,-cy*sp*sr-sy*cr,-cy*sp*cr+sy*sr,sy*cp,-sy*sp*sr+cy*cr,-sy*sp*cr-cy*sr,sp,cp*sr,cp*cr];}
 function settings(){const gain=Number($('gain').value);if(!Number.isFinite(gain)||gain< -60||gain>24)throw Error('Output level must be -60 to +24 dB');for(const k of ['yaw','pitch','roll'])if(!Number.isFinite(Number($(k).value))||Math.abs(Number($(k).value))>180)throw Error('Rotation must be between -180 and +180 degrees');return {matrix:rotation(),gain:Math.fround(10**(gain/20)),clamp:$('clamp').checked};}
 async function makeGraph(ctx,output,monitor){
  const input=ctx.createGain();input.channelCount=4;input.channelCountMode='explicit';input.channelInterpretation='discrete';const split=ctx.createChannelSplitter(4),merge=ctx.createChannelMerger(4);input.connect(split);const nodes=[];
  for(let row=0;row<3;row++)for(let col=0;col<3;col++){const node=ctx.createGain();split.connect(node,xyz[col]);node.connect(merge,0,xyz[row]);nodes.push(node);}
  const w=ctx.createGain();split.connect(w,0);w.connect(merge,0,0);
  const unclamped=ctx.createGain(),clamped=ctx.createGain(),shaper=ctx.createWaveShaper();shaper.channelCount=4;shaper.channelCountMode='explicit';shaper.channelInterpretation='discrete';shaper.curve=new Float32Array([-1,0,1]);merge.connect(unclamped);merge.connect(shaper);shaper.connect(clamped);
  const renderer=Omnitone.createFOARenderer(ctx,{channelMap:[0,1,2,3]});unclamped.connect(renderer.input);clamped.connect(renderer.input);const volume=ctx.createGain();renderer.output.connect(volume);volume.connect(output);await renderer.initialize();
  function update(s,smooth=false){const t=ctx.currentTime,set=(node,value)=>{if(smooth)node.gain.setTargetAtTime(value,t,.02);else node.gain.setValueAtTime(value,t);};for(let i=0;i<9;i++)set(nodes[i],s.matrix[i]*s.gain);set(w,s.gain);set(unclamped,s.clamp?0:1);set(clamped,s.clamp?1:0);volume.gain.value=monitor?Math.max(0,Math.min(100,Number($('monitor-level').value)||0))/100:1;}
  return {input,update,volume,disconnect(){input.disconnect();volume.disconnect();}};
 }
 function selected(){return entries.find(g=>g.id===select.value);}
 function controls(){const ready=!!selected(),blocked=busy||exporting||loading;play.disabled=!ready||blocked;stop.disabled=!source;seek.disabled=!buffer||blocked;select.disabled=!entries.length||blocked;exportButton.disabled=!ready||blocked;play.textContent=source?'Pause':'Play';}
 function position(){return source?Math.min(buffer.duration,offset+context.currentTime-started):offset;}
 function time(){const t=position();window.SpatialSphere?.setPlayback(select.value,t);seek.value=t;$('audio-time').textContent=`${Math.floor(t/60)}:${(t%60).toFixed(1).padStart(4,'0')}`;}
 function halt(reset=false){const t=position();if(source){source.onended=null;source.stop();source.disconnect();source=null;}offset=reset?0:t;clearInterval(timer);time();controls();}
 async function load(){const g=selected();if(!g)throw Error('Select a converted recording');if(buffer&&loaded===g.result.preview_audio)return;halt(true);buffer=null;loaded=null;loading=true;controls();status.textContent='Preparing headphone preview…';try{const bytes=await g.result.preview_audio.arrayBuffer(),view=new DataView(bytes),rate=g.result.analysis.sample_rate,frames=g.result.analysis.frames;buffer=context.createBuffer(4,frames,rate);for(let ch=0;ch<4;ch++){const a=buffer.getChannelData(ch);for(let f=0;f<frames;f++)a[f]=view.getFloat32((frames*16+48>0xffffffff?92:56)+(f*4+ch)*4,true);}loaded=g.result.preview_audio;seek.max=buffer.duration;offset=0;time();status.textContent='Ready · binaural headphones · current output rotation and level.';}finally{loading=false;controls();}}
 async function ensure(){if(!context){context=new (window.AudioContext||window.webkitAudioContext)();}await context.resume();if(!graph)graph=await makeGraph(context,context.destination,true);await load();graph.update(settings());}
 play.addEventListener('click',async()=>{try{if(source){halt();return;}await ensure();if(offset>=buffer.duration)offset=0;source=context.createBufferSource();source.buffer=buffer;source.connect(graph.input);started=context.currentTime;source.onended=()=>{source.disconnect();source=null;offset=0;clearInterval(timer);time();controls();};source.start(0,offset);time();timer=setInterval(time,100);controls();status.textContent='Playing binaural preview · rotation updates live.';}catch(e){status.textContent=e.message;loading=false;controls();}});
 stop.addEventListener('click',()=>halt(true));seek.addEventListener('input',()=>{const running=!!source,target=Number(seek.value);halt();offset=target;time();if(running)play.click();});
 select.addEventListener('change',()=>{halt(true);buffer=null;loaded=null;seek.max=0;status.textContent='Press Play to prepare this recording.';time();controls();});
 const update=()=>{if(graph)try{graph.update(settings(),true);}catch(e){status.textContent=e.message;}};for(const k of ['yaw','pitch','roll','gain','clamp','monitor-level'])$(k).addEventListener('input',update);$('rotation-reset').addEventListener('click',update);
 // Sphere gestures change numeric inputs directly; observe their pointer events.
 $('spatial-sphere').addEventListener('pointermove',update);$('spatial-sphere').addEventListener('pointerup',update);$('gain-reset').addEventListener('click',update);
 function wavStereo(audio){const frames=audio.length,bytes=frames*8;if(bytes+48>0xffffffff)throw Error('Stereo export exceeds the WAV size limit');const h=new ArrayBuffer(56),v=new DataView(h);function text(o,s){for(let i=0;i<s.length;i++)v.setUint8(o+i,s.charCodeAt(i));}text(0,'RIFF');v.setUint32(4,bytes+48,true);text(8,'WAVE');text(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,3,true);v.setUint16(22,2,true);v.setUint32(24,audio.sampleRate,true);v.setUint32(28,audio.sampleRate*8,true);v.setUint16(32,8,true);v.setUint16(34,32,true);text(36,'fact');v.setUint32(40,4,true);v.setUint32(44,frames,true);text(48,'data');v.setUint32(52,bytes,true);const parts=[h],l=audio.getChannelData(0),r=audio.getChannelData(1);for(let pos=0;pos<frames;pos+=65536){const n=Math.min(65536,frames-pos),a=new Float32Array(n*2);for(let i=0;i<n;i++){a[i*2]=l[pos+i];a[i*2+1]=r[pos+i];}parts.push(a.buffer);}return new Blob(parts,{type:'audio/wav'});}
 exportButton.addEventListener('click',async()=>{let offlineGraph;try{halt();await ensure();const s=settings(),g=selected();exporting=true;controls();status.textContent='Rendering binaural stereo…';const offline=new OfflineAudioContext(2,buffer.length+512,buffer.sampleRate);offlineGraph=await makeGraph(offline,offline.destination,false);offlineGraph.update(s);const node=offline.createBufferSource();node.buffer=buffer;node.connect(offlineGraph.input);node.start();const stereo=await offline.startRendering(),blob=wavStereo(stereo),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=g.name.replace(/[^\w .()\-]/g,'_')+'_binaural.wav';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);let peak=0;for(let ch=0;ch<2;ch++)for(const value of stereo.getChannelData(ch))peak=Math.max(peak,Math.abs(value));status.textContent=`Binaural WAV ready · ${buffer.sampleRate} Hz · 32-bit float · 512-sample filter tail · peak ${peak? (20*Math.log10(peak)).toFixed(1):'−∞'} dBFS.`;}catch(e){status.textContent=e.message;}finally{offlineGraph?.disconnect();exporting=false;controls();}});
 window.BinauralPreview={refresh(groups,isBusy){busy=isBusy;const next=groups.filter(g=>g.result?.preview_audio);if(source&&(busy||!next.some(g=>g.id===select.value)))halt();if(next.map(g=>g.id).join()!==entries.map(g=>g.id).join()){const previous=select.value;entries=next;select.replaceChildren();if(!entries.length){const o=document.createElement('option');o.textContent='Convert a recording first';select.append(o);}for(const g of entries){const o=document.createElement('option');o.value=g.id;o.textContent=g.name;select.append(o);}if(entries.some(g=>g.id===previous))select.value=previous;}else entries=next;if(loaded&&selected()?.result.preview_audio!==loaded){halt(true);buffer=null;loaded=null;}controls();}};
 controls();
})();
