/* Offline canvas visualization and sound-field rotation controls. */
(()=>{
 const canvas=document.getElementById('spatial-sphere'),ctx=canvas.getContext('2d'),select=document.getElementById('sphere-recording'),slider=document.getElementById('sphere-time'),status=document.getElementById('sphere-status');
 const texture=document.createElement('canvas');texture.width=texture.height=440;const textureContext=texture.getContext('2d');
 const angle=k=>Number(document.getElementById(k).value)||0;let entries=[],busy=false,drag=null;
 function matrix(){const y=angle('yaw')*Math.PI/180,p=angle('pitch')*Math.PI/180,r=angle('roll')*Math.PI/180,cy=Math.cos(y),sy=Math.sin(y),cp=Math.cos(p),sp=Math.sin(p),cr=Math.cos(r),sr=Math.sin(r);return [cy*cp,-cy*sp*sr-sy*cr,-cy*sp*cr+sy*sr,sy*cp,-sy*sp*sr+cy*cr,-sy*sp*cr-cy*sr,sp,cp*sr,cp*cr];}
 function selected(){return entries.find(e=>e.id===select.value);}
 function draw(){
  ctx.setTransform(1,0,0,1,40,0);ctx.clearRect(-40,0,640,560);ctx.fillStyle='#000';ctx.fillRect(-40,0,640,560);const m=matrix(),entry=selected(),preview=entry?.result.analysis.spatial_preview,idx=Number(slider.value),cov=preview?.covariance[idx];
  const pixels=ctx.createImageData(440,440),energies=new Float64Array(440*440);let maximum=0;
  for(let y=0;y<440;y++)for(let x=0;x<440;x++){const u=(x-219.5)/210,v=(219.5-y)/210,r2=u*u+v*v;if(r2>1)continue;const n=[Math.sqrt(1-r2),-u,v],a=[1,m[0]*n[0]+m[3]*n[1]+m[6]*n[2],m[1]*n[0]+m[4]*n[1]+m[7]*n[2],m[2]*n[0]+m[5]*n[1]+m[8]*n[2]];let e=0;if(cov)for(let i=0;i<4;i++)for(let j=0;j<4;j++)e+=a[i]*cov[i*4+j]*a[j];e=Math.max(0,e);energies[y*440+x]=e;maximum=Math.max(maximum,e);}
  for(let y=0;y<440;y++)for(let x=0;x<440;x++){const r2=((x-219.5)/210)**2+((y-219.5)/210)**2;if(r2>1)continue;const i=(y*440+x)*4,c=cov&&maximum>0?Math.round(24+220*Math.sqrt(energies[y*440+x]/maximum)):24;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=c;pixels.data[i+3]=255;}textureContext.putImageData(pixels,0,0);ctx.drawImage(texture,60,60);
  ctx.strokeStyle='#888';ctx.lineWidth=1;ctx.beginPath();ctx.arc(280,280,210,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#555';for(const radius of [105,182]){ctx.beginPath();ctx.ellipse(280,280,radius,210,0,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.ellipse(280,280,210,radius,0,0,Math.PI*2);ctx.stroke();}ctx.beginPath();ctx.moveTo(70,280);ctx.lineTo(490,280);ctx.moveTo(280,70);ctx.lineTo(280,490);ctx.stroke();
  ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(280,280,245,0,Math.PI*2);ctx.stroke();const r=angle('roll')*Math.PI/180;ctx.beginPath();ctx.moveTo(280+231*Math.sin(r),280-231*Math.cos(r));ctx.lineTo(280+255*Math.sin(r),280-255*Math.cos(r));ctx.stroke();ctx.font='17px sans-serif';ctx.textAlign='center';ctx.fillStyle='#fff';ctx.fillText('UP',280,18);ctx.fillText('LEFT',0,285);ctx.fillText('RIGHT',560,285);ctx.fillText('DOWN',280,550);ctx.fillStyle='#000';ctx.fillRect(250,267,60,24);ctx.fillStyle='#fff';ctx.fillText('FRONT',280,285);
  const seconds=(preview?.seconds_per_bin||0)*idx;document.getElementById('sphere-time-label').textContent=`${Math.floor(seconds/60)}:${Math.floor(seconds%60).toString().padStart(2,'0')}`;
  status.hidden=!preview;status.textContent=preview?`Relative energy · ${preview.seconds_per_bin.toFixed(2)} s window. Preview follows current rotation.`:'';
 }
 function sync(){const p=selected()?.result.analysis.spatial_preview;slider.max=Math.max(0,(p?.covariance.length||1)-1);slider.value=Math.min(Number(slider.value),Number(slider.max));slider.disabled=!p||busy;select.disabled=!entries.length||busy;draw();}
 window.SpatialSphere={refresh(groups,isBusy){busy=isBusy;const next=groups.filter(g=>g.result?.analysis?.spatial_preview);if(next.map(g=>g.id).join()!==entries.map(g=>g.id).join()){const previous=select.value;entries=next;select.replaceChildren();if(!entries.length){const o=document.createElement('option');o.textContent='No converted recordings';select.append(o);}for(const g of entries){const o=document.createElement('option');o.value=g.id;o.textContent=g.name;select.append(o);}if(entries.some(g=>g.id===previous))select.value=previous;}else entries=next;sync();}};
 select.addEventListener('change',()=>{slider.value=0;sync();});slider.addEventListener('input',draw);for(const k of ['yaw','pitch','roll'])document.getElementById(k).addEventListener('input',draw);document.getElementById('rotation-reset').addEventListener('click',draw);
 function position(e){const r=canvas.getBoundingClientRect();return [(e.clientX-r.left)*640/r.width-320,(e.clientY-r.top)*560/r.height-280];}
 const wrap=v=>((v+180)%360+360)%360-180;
 canvas.addEventListener('pointerdown',e=>{if(busy)return;const [x,y]=position(e);if(Math.hypot(x,y)>265)return;drag={x,y,yaw:angle('yaw'),pitch:angle('pitch'),roll:angle('roll'),ring:Math.hypot(x,y)>220,a:Math.atan2(x,-y)};canvas.setPointerCapture(e.pointerId);});
 canvas.addEventListener('pointermove',e=>{if(!drag)return;const [x,y]=position(e);if(drag.ring)document.getElementById('roll').value=wrap(drag.roll+(Math.atan2(x,-y)-drag.a)*180/Math.PI).toFixed(1);else{document.getElementById('yaw').value=wrap(drag.yaw-(x-drag.x)*.4).toFixed(1);document.getElementById('pitch').value=Math.max(-180,Math.min(180,drag.pitch-(y-drag.y)*.4)).toFixed(1);}draw();});
 canvas.addEventListener('pointerup',()=>drag=null);canvas.addEventListener('pointercancel',()=>drag=null);draw();
})();
